version: 0.2

phases:
  install:
    commands:
      - echo "Java version"
      - java -version

      - echo "Maven version"
      - mvn -version

      - echo "Chrome version"
      - google-chrome --version || true

      - echo "Cleaning chromedriver conflicts"
      - sudo rm -f /usr/local/bin/chromedriver || true
      - sudo rm -f /usr/bin/chromedriver || true

  build:
    commands:
      - mvn clean test