version: 0.2

phases:

  install:
    commands:
      - java -version
      - mvn -version

  build:
    commands:
      - mvn clean test

reports:
  selenium-report:
    files:
      - TEST-*.xml
    base-directory: target/surefire-reports
    file-format: JUNITXML